version: "3.9"
services:
  homer:
    image: b4bz/homer
    build: .
    container_name: homer
    volumes:
      - ./assets:/www/assets
    ports:
      - 8080:8080
    user: root
    environment:
      - INIT_ASSETS=1 # default
